Feature/peer 4 login via intranet
joshsoftware/peerly-backend pull request #4
Opened 2024-06-28 06:57 UTC by SharyuMarwadi

2024-07-22 05:43 UTC, SharyuMarwadi commented on internal/api/user.go
> +		validateResp, err := userSvc.ValidatePeerly(req.Context(), authToken)
Done

2024-07-22 05:44 UTC, SharyuMarwadi commented on internal/api/validation/user.go
> +		fmt.Println("Invalid user data")
Done

2024-07-22 05:44 UTC, SharyuMarwadi commented on internal/app/users/service.go
> +	GetUserListIntranet(ctx context.Context, reqData dto.GetUserListReq) (data []dto.IntranetUserData, err error)
Done

2024-07-22 05:44 UTC, SharyuMarwadi commented on internal/app/users/service.go
> +	validationReq, err := http.NewRequest("POST", "https://pg-stage-intranet.joshsoftware.com/api/peerly/v1/sessions/login", nil)
Done

2024-07-22 05:44 UTC, SharyuMarwadi commented on internal/app/users/service.go
> +	url := fmt.Sprintf("https://pg-stage-intranet.joshsoftware.com/api/peerly/v1/users/%d", req.UserId)
Done

2024-07-22 05:44 UTC, SharyuMarwadi commented on internal/app/users/service.go
> +	intranetReq, err := http.NewRequest("GET", url, nil)
Done

2024-07-22 05:44 UTC, SharyuMarwadi commented on internal/pkg/apperrors/errors.go
> +	case InvalidId, JSONParsingErrorReq, TextFieldBlank, InvalidCoreValueData, InvalidParentValue, DescFieldBlank, UniqueCoreValue, RepeatedUser:
Done

2024-07-22 05:44 UTC, SharyuMarwadi commented on internal/pkg/constants/user.go
> +var PerPage = 400
Done

2024-07-22 05:45 UTC, SharyuMarwadi commented on internal/pkg/dto/users.go
> +	Id   int
Done

2024-07-22 05:45 UTC, SharyuMarwadi commented on internal/pkg/middleware/jwtMiddleware.go
> +		fmt.Println("authtoken: ", authToken)
It was for debugging, removed it

2024-07-22 05:48 UTC, SharyuMarwadi commented on internal/repository/postgresdb/coreValues.go
> +		logger.Errorf("error in generating squirrel query, err: %s", err.Error())
There are different custom errors for different situations in this function. Hence cannot wrap and return it

2024-07-23 09:08 UTC, yama11299 requested changes

2024-07-23 09:08 UTC, yama11299 commented on internal/app/users/service.go
> +	url := config.IntranetBaseUrl() + fmt.Sprintf("/api/peerly/v1/users?page=%d&per_page=%d", reqData.Page, constants.DefaultPageSize)
constant is defined for this path right? use it here.

2024-07-23 09:08 UTC, yama11299 commented on internal/pkg/constants/system.go
> +	IntanetAuthToken       = "INTRANET_AUTH_TOKEN"
IntanetAuthToken -> IntranetAuthToken

2024-07-23 09:53 UTC, SharyuMarwadi commented on internal/pkg/constants/system.go
> +	IntanetAuthToken       = "INTRANET_AUTH_TOKEN"
Done

2024-07-23 12:42 UTC, yama11299 commented
There are still some small changes but approving for now.

2024-07-23 12:46 UTC, SharyuMarwadi commented
Okay

2024-07-23 12:48 UTC, merged